# Generated by Django 6.0 on 2025-12-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('flavor_id', models.AutoField(primary_key=True, serialize=False)),
                ('flavor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'flavor',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='SweetType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sweet_type',
            },
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('sweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('composition', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.brand')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.flavor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.manufacturer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.sweettype')),
            ],
            options={
                'db_table': 'sweet',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('sweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.sweet')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
